---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: centos7
    image: centos:7
  - name: centos8
    image: centos:8
  - name: ubuntu1804
    image: ubuntu:18.04
  - name: ubuntu1910
    image: ubuntu:19.10
  - name: ubuntu1904
    image: ubuntu:19.04
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: debian
    image: debian:buster
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        recon_findomain_username: root
        recon_findomain_home_dir: /root
        recon_findomain_fb_token: fb_token
        recon_findomain_spyse_token: spyse
        recon_findomain_virustotal_token: vt
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
